routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('register2', function () {
    return view('auth.register2');
});

Route::post('regis/insert', 'RegistersController@index');

//student
Route::get('filefull', function () {
    $idu = Auth::user()->id;
    $data['project'] = DB::table('membersprojects')
        ->select('projects_id')
        ->where('students_id', $idu)
        ->get();
    $data['fileproject'] = DB::table('membersprojects')
        ->leftJoin('projects', 'membersprojects.projects_id', 'projects.id')
        ->where('membersprojects.students_id', $idu)
        ->get();
    //dd($data['fileproject']);
    return view('page.student.upFileFull', $data);
});
Route::post('upfilefull/{id}', 'myProjectController@store');
Route::post('Requestexam/{id}', 'RequestexamController@index');
Route::post('Requestexams/addexam', 'RequestexamController@store');
Route::get('menu/project', function () {
    return view('page.student.menuproject');
});
Route::post('studentFileEnd/{id}', 'RequestexamController@updateFileEnd');
Route::post('upstatus_pro2/{id}', 'AdminController@upstatus_exam');

Route::get('exam/show', 'RequestexamController@showexam');
Route::get('exam/showcalendar', 'RequestexamController@showexamcalendar');

Route::get('exam/showstatus', 'RequestexamController@showstatus');

Route::resource('Projectall', 'ProjectallController');
Route::resource('stdinfor', 'StdinformationController');
Route::resource('adviser', 'AdviserController');
Route::resource('myProject', 'myProjectController');

Route::resource('editproject', 'EditProjectController');

Route::get('std1', function () {
    return view('page.student.std1');
});
Route::resource('createProject', 'createProjectController');

Route::get('std5', function () {
    return view('page.student.std5');
});

Route::get('studentHome', function () {
    return view('page.student.studentHome');
});



Route::get('/MidtermExam', function () {
    return view('page/student/MidtermExam');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


//profesors
Route::post('upstatus_adviser/{project_nameth}', 'ConsultantRequestController@upstatus_adviser');
Route::get('detel_adviser/{project_nameth}', 'ConsultantRequestController@detel');
Route::resource('ConsultantRequest', 'ConsultantRequestController');
Route::post('exam/addpoin', 'examofficersController@addpoinofficer');

Route::post('upstatus_studentexam/{project_name}', 'StudentExamOfficerController@upstatus_adviser');
Route::get('detel_studentexam/{project_name}', 'StudentExamOfficerController@detel');
Route::get('examsoff/poin/{exam_id}', 'examofficersController@addpoin');
Route::get('examsoff/poin/show/{id}', 'examofficersController@showpoin');
Route::get('showcalandarexam/{id}', 'ExamController@showcalandarexam');
Route::get('showcalandarexam/officer/{id}', 'examofficersController@showcalandarexam');

Route::resource('StudentExamOfficer', 'StudentExamOfficerController');
Route::resource('examofficers', 'examofficersController');

Route::resource('ListProjectsConsult', 'ListProjectsConsultController');

Route::get('DocumentProjectConsultant', function () {
    return view('page.profesor.DocumentProjectConsultant');
});
Route::get('profesHome', function () {
    return view('page.profesor.profesHome');
});

Route::get('managemember', function () {
    return view('page.profesor.managemember');
});
Route::get('/', function () {
    return view('auth.login');
});
Route::resource('createExam', 'ExamController');
Route::resource('Exam', 'ExamController');




//admin 
Route::post('upstatus_studentexamAD/{project_name}', 'StudentExamAdminController@upstatus_adviser');
Route::get('detel_studentexamAD/{project_name}', 'StudentExamAdminController@detel');
Route::resource('StudentExamAdmin', 'StudentExamAdminController');

Route::post('upstatus_admin/{project_name}', 'ConsultantRequestAdminController@upstatus_admin');
Route::get('detel_admin/{project_name}', 'ConsultantRequestAdminController@detel');
Route::resource('ConsultantRequestAdmin', 'ConsultantRequestAdminController');
Route::patch('Examadminuppoin/{exam_id}', 'ExamadminController@update');

Route::get('detel/{project_name}', 'AdminController@detel');
Route::get('exam/showexam', 'ExamadminController@index');
Route::get('exam/manage/{id}', 'ExamadminController@manage');
Route::delete('exam/editmanage/{id}', 'ExamadminController@destroy');
Route::post('Exam/manage/create', 'ExamadminController@managecreate');
Route::get('examsadmin/poin/{id}', 'ExamadminController@addpoin');
Route::post('examadmin/addpoin', 'ExamadminController@addpoinadmin');
Route::get('examsadmin/poin/show/{id}', 'ExamadminController@showpoin');
Route::get('examsadmin/seccess/{id}', 'ExamadminController@seccess');
Route::get('examsadmin/report/{id}', 'ExamadminController@report');


Route::resource('requesteexam', 'AdminController');
Route::post('upstatus1/{project_name}', 'AdminController@upstatus1');

Route::resource('Adviser', 'AdviserController');

Route::get('/allproject', 'AdminController@allproject')->name('allproject');
Route::get('/allprojectAdmin', 'AdminController@allprojectAdmin')->name('allprojectAdmin');

Route::resource('officer', 'OfficerController');
Route::post('addofficer', 'OfficerController@store');
Route::resource('Addadviser', 'AdviserController');
Route::post('createAdviser', 'AdviserController@store');
Route::resource('project_type', 'ProjecttypesController');

Route::resource('requestexam2', 'RequestexamController');
Route::post('add/status/{id}', 'RequesteexamController@upstatus');
Route::resource('member', 'Member1Controller');

Route::delete('/destroy/{id}', 'Member1Controller@destroy');



Route::get('createmember', function () {
    return view('auth.register');
});

resources/views/page/admin/AddAdviser.blade.php
@extends('Layout.master')
@section('title')
    เพิ่มข้อมูลอาจารย์
@endsection('title')

@section('content')

    <div class="container">
        <div class="table-responsive">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">เพิ่มข้อมูล อาจารย์</div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif

                        <form action="{{ url('createAdviser') }}" method="post">
                            {{ csrf_field() }}
                            <div class="form-row">

                                <input type="hidden" name="type" value="officer">

                                <div class="form-group col-md-4">
                                    <label for="inputPassword4">username</label>
                                    <input type="text" class="form-control" name="name" required="">
                                </div>
                                <div class="form-group col-md-4">
                                    <label for="inputPassword4">email</label>
                                    <input type="email" class="form-control" name="email" required="">
                                </div>
                                <div class="form-group col-md-4">
                                    <label for="inputPassword4">password</label>
                                    <input type="password" class="form-control" name="password" required="">
                                </div>
                                <div class="form-group col-md-4">
                                    <label for="inputPassword4">รหัสอาจารย์</label>
                                    <input type="text" class="form-control" name="adviser_id" 
                                        title="กรอกตัวเลขเท่านั้น" required>
                                </div>
                                <div class="form-group col-md-4">
                                    <label for="inputPassword4">ชื่อ</label>
                                    <input type="text" class="form-control" name="adviser_name" pattern=^[ก-๏\s]+$
                                        title="กรอกตัวอักษรเท่านั้น" required>
                                </div>
                                <div class="form-group col-md-4">
                                    <label for="inputPassword4">สกุล</label>
                                    <input type="text" class="form-control" name="adviser_lastname" pattern=^[ก-๏\s]+$
                                        title="กรอกตัวอักษรเท่านั้น" required>
                                </div>
                             
                                <input type="hidden" name="off_id" value="1">
                                
                            </div>
                            <div class=" text-center">
                                <button type="submit" class="btn btn-primary "
                                    onclick="return confirm('ต้องการเพิ่มข้อมูลใช่ หรือ ไม่')">เพิ่มข้อมูล</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="table-responsive">
            <table class="table  tabel-bordered  table-striped">
                <tr>
                    
                    <th>รหัสอาจารย์</th>
                    <th>ชื่อ</th>
                    <th>สกุล</th>
                    <th>แก้ไข</th>
                    <th>ลบ</th>
                </tr>
                @foreach ($adviser as $row)
                    <tr>
                        
                        <td>{{ $row->adviser_id }}</td>
                        <td>{{ $row->adviser_name }}</td>
                        <td>{{ $row->adviser_lastname }}</td>
                        
                        <td>
                            <a href="{{ action('AdviserController@edit', $row->id) }}" class="btn btn-warning"><i
                                    class="fa fa-wrench"></i></a>
                        </td>
                        <td>
                            <form method="post" class="delete_form"
                                action="{{ action('AdviserController@destroy', $row->id) }}">
                                {{ csrf_field() }}
                                <input type="hidden" name="_method" value="DELETE">
                                <button class="btn btn-danger" type="submit"
                                    onclick="return confirm('ต้องการลบข้อมูลใช่ หรือ ไม่')"><i
                                        class="fa fa-trash"></i></button>
                            </form>
                        </td>
                    </tr>
                @endforeach
            </table>
        </div>
    </div>
@endsection

resources/views/page/admin/CreateExam.blade.php
@extends('Layout.master')
@section('title')
@endsection('title')
@section('content')


<div class="section-title">
    <h2>INFORMATION TECHNOLOGY</h2>
    <div class="row">
        <!-- &nbsp;&nbsp; <a class="btn btn-info active">สร้างประกาศสอบ</a>&nbsp;&nbsp; -->
        <!-- <a class="btn btn-info" href="exam/manage">จัดการการสอบ</a> -->
    </div>
</div>
<div class="container">
    @if (session('status'))
    <div class="alert alert-success" role="alert">
        {{ session('status') }}
    </div>
    @endif
    <form action="{{ route('createExam.store') }}" method="post">
        {{ csrf_field() }}
        <div class="form-row">
            <input type="hidden" name="status" id="" value="ใช้งาน">
            <div class="form-group col-md-5">
                <label for="topic">เลือกสอบ</label>
                <select class="form-control" name="topic" required="">
                    <option selected>เลือก...</option>
                    <option value="midterm">กลางภาค</option>
                    <option value="final">ปลายภาค</option>
                </select>
            </div>
            <div class="form-group col-md-5">
                <label for="typeproject">โปรเจค</label>
                <select class="form-control" name="typeproject" required="">
                    <option selected>เลือก...</option>
                    <option value="Project1">Project1</option>
                    <option value="Project2">Project2</option>
                </select>
                <br>
                <br>
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-12">
                <label for="yearedu">ปีการศึกษา</label>
                <div class="row">
                    <div class="form-group col-md-3">
                        <input type="text" class="form-control" name="yearedu" placeholder="ตัวอย่าง 2/2562" required="">
                    </div>
                </div>
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-4">
                <label for="dateexamstart">วันที่เริ่มสอบ</label>
                <input type="date" class="form-control" min="<?php echo date('Y-m-d'); ?>" name="dateexamstart" required="">
            </div>
            <div class="form-group col-md-4">
                <label for="dateexamend">ถึงวันที่</label>
                <input type="date" class="form-control" min="<?php echo date('Y-m-d'); ?>" name="dateexamend" required="">
            </div>
        </div>

        <div class="form-row">
            <div class="form-group col-md-4">
                <label for="dateregisstart">วันขอขึ้นสอบ</label>
                <input type="date" class="form-control" min="<?php echo date('Y-m-d'); ?>" name="dateregisstart" required="">
            </div>
            <div class="form-group col-md-4">
                <label for="dateregisend">ถึงวันที่</label>
                <input type="date" class="form-control" min="<?php echo date('Y-m-d'); ?>" name="dateregisend" required="">
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-8">
                <div class="form-group">
                    <label for="detail">รายละเอียดการสอบ</label>
                    <textarea class="form-control" rows="5" id="comment" name="detail" required=""></textarea>
                </div>
            </div>
        </div>

        <div class=" text-center">
            <button type="submit" class="btn btn-primary " onclick="return confirm('ต้องการเพิ่มข้อมูลใช่ หรือ ไม่')"><i class="bx bx-plus-circle">เพิ่มข้อมูล</i></button>
        </div>
    </form>
</div>

<hr>


<div class="table-responsive">
    <table class="table  tabel-bordered  table-striped">
        <tr>
            <th>การสอบ</th>
            <th>โปรเจ็ค</th>
            <th>ปีการศึกษา</th>
            <th>วันที่เริ่มสอบ</th>
            <th>จัดการสอบ</th>
            <th>Reportคะแนน</th>
            <th>ตารางเวลาสอบ</th>
            <th>แก้ไข</th>
            <th>ลบ</th>
        </tr>
        @foreach ($addexam as $row)
        <tr>
            <td>@if($row->topic == 'midterm')กลางภาค
                @elseif($row->topic == 'final')ปลายภาค
                @endif
            </td>
            <td>{{ $row->typeproject }}</td>
            <td>{{ $row->yearedu }}</td>
            <td>{{ $row->dateexamstart }} - {{ $row->dateexamend }}</td>
            <td> <a class="btn btn-info" href="{{url('exam/manage', $row->id)}}"><i class="fas fa-tasks"></i></a></td>
            <td>
                <a href="{{ url('examsadmin/report', $row->id) }}" class="btn btn-info"><i class="fas fa-print"></i></a>
            </td>
            <td>
                <a href="{{ url('showcalandarexam', $row->id) }}" class="btn btn-warning"><i class="fa fa-print"></i></a>
            </td>
            <td>
                <a href="{{ action('ExamController@edit', $row->id) }}" class="btn btn-warning"><i class="fa fa-wrench"></i></a>
            </td>
            <td>
                <form method="post" class="delete_form" action="{{ action('ExamController@destroy', $row->id) }}">
                    {{ csrf_field() }}
                    <input type="hidden" name="_method" value="DELETE">
                    <button class="btn btn-danger" type="submit" onclick="return confirm('ต้องการลบข้อมูลใช่ หรือ ไม่')"><i class="fa fa-trash"></i></button>
                </form>
            </td>
        </tr>
        @endforeach
    </table>
</div>




@endsection

resources/views/page/admin/EditAdviser.blade.php
@extends('Layout.master')
@section('title')
    แก้ไขข้อมูลอาจารย์
@endsection('title')

@section('content')


    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">เพิ่มข้อมูล อาจารย์</div>
                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif

                        <form action="{{ action('AdviserController@update', $adviser->id) }}" method="post">
                            {{ csrf_field() }}
                            {{ method_field('PATCH') }}
                            <div class="form-row">

                                <div class="form-group col-md-4">
                                    <label for="inputPassword4">รหัสอาจารย์</label>
                                    <input type="text" class="form-control" name="adviser_id"
                                        value="{{ $adviser->adviser_id }}" pattern="[0-9]{1,}" title="กรอกตัวเลขเท่านั้น"
                                        required>
                                </div>
                                <div class="form-group col-md-4">
                                    <label for="inputPassword4">ชื่อ</label>
                                    <input type="text" class="form-control" name="adviser_name"
                                        value="{{ $adviser->adviser_name }}" pattern="[A-Za-zก-ฮ]{1,}"
                                        title="กรอกตัวอักษรเท่านั้น" required>
                                </div>
                                <div class="form-group col-md-4">
                                    <label for="inputPassword4">สกุล</label>
                                    <input type="text" class="form-control" name="adviser_lastname"
                                        value="{{ $adviser->adviser_lastname }}" pattern="[0-9]{1,}"
                                        title="กรอกตัวเลขเท่านั้น" required>
                                </div>


                            </div>
                            <div class=" text-center">
                                <button type="submit" class="btn btn-primary "
                                    onclick="return confirm('ต้องการแก้ไขข้อมูลใช่ หรือ ไม่')">เพิ่มข้อมูล</button>
                            </div>
                            <input type="hidden" name="_method" value="PATCH">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/page/admin/EditOfficer.blade.php
@extends('Layout.master')
@section('title')
    แก้ไขข้อมูลอาจารย์
@endsection('title')

@section('content')


    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">แก้ไขข้อมูลอาจารย์</div>
                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif
                        @foreach ($officer as $officer)

                            <form action="{{ action('OfficerController@update', $officer->id) }}" method="post">
                                {{ csrf_field() }}
                                {{ method_field('PATCH') }}
                                <div class="form-row">
                                    <div class="form-group col-md-4">
                                        <label for="inputPassword4">ชื่อ</label>
                                        <input type="text" class="form-control" name="officer_name"
                                            value="{{ $officer->officer_name }}">
                                    </div>
                                    <div class="form-group col-md-4">
                                        <label for="inputPassword4">สกุล</label>
                                        <input type="text" class="form-control" name="officer_lastname"
                                            value="{{ $officer->officer_lastname }}">
                                    </div>
                                    <div class="form-group col-md-4">
                                        <label for="inputPassword4">email</label>
                                        <input type="text" class="form-control" name="email" value="{{ $officer->email }}">
                                    </div>
                                    <div class="form-group col-md-4">
                                        <label for="inputPassword4">password</label>
                                        <input type="text" class="form-control" name="password" value="{{ $officer->password }}">
                                    </div>
                                    <div class="form-group col-md-4">
                                        <label for="inputPassword4">เบอร์</label>
                                        <input type="text" class="form-control" name="tel_off"
                                            value="{{ $officer->tel_off }}">
                                    </div>

                                </div>
                                <div class=" text-center">
                                    <button type="submit" class="btn btn-primary "
                                        onclick="return confirm('ต้องการแก้ไขข้อมูลใช่ หรือ ไม่')">เพิ่มข้อมูล</button>
                                </div>
                                <input type="hidden" name="_method" value="PATCH">
                            </form>
                        @endforeach
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/page/admin/addproject_type.blade.php
@extends('Layout.master')
@section('title')
เพิ่มประเภทโปรเจ็ค
@endsection('title')

@section('content')
<div class="section-title">
    <h2>INFORMATION TECHNOLOGY</h2>
</div>



<form action="{{ route('project_type.store') }}" method="post">
    {{ csrf_field() }}
    <div class="form-row">
        <div class="form-group col-md-4">
            <label for="inputPassword4">ประเภทโปรเจค</label>
            <input type="text" class="form-control" name="projecttype_name" required="" placeholder="ตัวอย่าง A">
        </div>
        <div class="form-group col-md-4">
            <label for="inputPassword4">รายละเอียดประเภทโปรเจค</label>
            <input type="text" class="form-control" name="projecttype_detail" required="" placeholder="ตัวอย่าง IOT">
        </div>

        <div class="table-responsive col-6">
            <label for="inputPassword4">อาจารย์ประจำประเภทโปรเจค</label>

            <table class="table  tabel-bordered  table-striped">
                <tr>
                    <th>ชื่อ</th>
                    <th>เลือก</th>
                </tr>
                @foreach ($officers as $row)
                <tr>
                    <td>{{ $row->officer_name }} {{ $row->officer_lastname }}</td>
                    <td><input class="form-check-input" name="officer_id[]" type="checkbox" value="{{ $row->id }}" id="flexCheckDefault"></td>
                </tr>
                @endforeach
            </table>
        </div>
    </div>
    <div class="form-group col-md-4"><br>
        <button type="submit" class="btn btn-primary text-center " onclick="return confirm('ต้องการเพิ่มข้อมูลใช่ หรือ ไม่')">เพิ่มข้อมูล</button>
    </div>

</form>

<div class="table-responsive mt-5">
    <table class="table  tabel-bordered  table-striped">
        <tr></tr>
        <th>ชื่อประเภทโปรเจ็ค</th>
        <th>แก้ไข</th>
        <th>ลบ</th>
        </tr>
        @foreach ($project_type as $row)
        <tr>

            <td>{{ $row->projecttype_name }}</td>

            <td>
                <a class="btn btn-warning" data-target="#modal-edit-customers{{$row->id}}" data-toggle="modal" id="modal-edit" title="Edit"><i class="fa fa-wrench"></i></a>

            </td>
            <td>
                <form method="post" class="delete_form" action="{{ action('ProjecttypesController@destroy', $row->id) }}">
                    {{ csrf_field() }}
                    <input type="hidden" name="_method" value="DELETE">
                    <button class="btn btn-danger" type="submit" onclick="return confirm('ต้องการลบข้อมูลใช่ หรือ ไม่')"><i class="fa fa-trash"></i></button>
                </form>
            </td>
        </tr>


        <div class="modal fade col-12" id="modal-edit-customers{{$row->id}}" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered modal-lg  w3-animate-right">
                <div class="modal-content">

                    <!-- Modal Header -->
                    <div class="modal-header">
                        <h4 class="">รายละเอียด</h4>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>
                    <input type="hidden" name="_token">
                    <form action="{{ action('ProjecttypesController@update', $row->id) }}" method="post">

                        @csrf
                        @method('PATCH')
                        <!-- Modal body -->
                        <div class="modal-body">

                            <div class="form-row">

                                <div class="form-group col-md-4">
                                    <label for="inputPassword4">ชื่อประเภทโปรเจ็ค</label>
                                    <input type="text" class="form-control" name="projecttype_name" value="{{ $row->projecttype_name }}">
                                </div>

                            </div>





                        </div>
                        <!-- Modal footer -->
                        <div class="modal-footer">
                            <button type="submit" class="w3-button w3-green w3-round-xlarge">แก้ไข</button>
                            <button type="button" class="w3-button w3-red w3-round-xlarge" data-dismiss="modal">ออก</button>
                        </div>
                </div>
            </div>
            </form>
            @endforeach
    </table>
</div>

@endsection

resources/views/page/admin/detelConsultantRequestAdmin.blade.php
@extends('Layout.master')
@section('title')
    รายละเอียดคำขอเป็นที่ปรึกษา
@endsection('title')

@section('content')

    <div class="section-title">
        <h2>รายละเอียดคำขอเป็นที่ปรึกษา</h2>
        @foreach ($projectss as $row)
            <h2>&nbsp;&nbsp;ชื่อโปรเจ็คภาษาไทย {{ $row->project_nameth }} <br>ชื่อโปรเจ็คภาษาอังกฤษ {{ $row->project_nameen }}</h2>
    </div>
    <div class="container">
        <div class="row">
            &nbsp;&nbsp;&nbsp;&nbsp;<h4>
                <p class="font-weight-bold">Pro1:Pro2 :</p>
            </h4>&nbsp;<h4>{{ $row->pro1_pro2_status }}</h4>
        </div>
        <div class="row mt-0">
            &nbsp;&nbsp;&nbsp;&nbsp;<h4>
                <p class="font-weight-bold">รายละเอียด :</p>
            </h4>&nbsp;<h4>{{ $row->project_detailth }}</h4>
        </div>
        <div class="row mt-0">
            &nbsp;&nbsp;&nbsp;&nbsp;<h4>
                <p class="font-weight-bold">รายละเอียด :</p>
            </h4>&nbsp;<h4>{{ $row->project_detailen }}</h4>
        </div>
        <div class="row mt-0">
            &nbsp;&nbsp;&nbsp;&nbsp;<h4>
                <p class="font-weight-bold">file_project :</p>
            </h4>&nbsp;<h4>{{ $row->file_project }}</h4>
        </div>
        <div class="row mt-0">
            &nbsp;&nbsp;&nbsp;&nbsp;<h4>
                <p class="font-weight-bold">file_full :</p>
            </h4>&nbsp;<h4>{{ $row->file_full }}</h4>
        </div>
        @endforeach
        <hr>
        @foreach ($student as $row)

            <div class="row mt-0">
                &nbsp;&nbsp;&nbsp;&nbsp;<h4>
                    <p class="font-weight-bold">รหัสนิสิต :</p>
                </h4>&nbsp;<h4>{{ $row->student_id }}</h4>
            </div>
            <div class="row mt-0">
                &nbsp;&nbsp;&nbsp;&nbsp;<h4>
                    <p class="font-weight-bold">ชื่อ-สกุล :</p>
                </h4>&nbsp;<h4>{{ $row->student_name }}&nbsp;&nbsp;{{ $row->student_lastname }}</h4>
            </div>
            <hr>


        @endforeach
    </div>

@endsection

resources/views/page/admin/editmember.blade.php
@extends('Layout.master')
@section('title')
แก้ไขการสมาชิก
@endsection('title')

@section('content')


<div class="card-header">เพิ่มข้อมูล อาจารย์</div>
<div class="card-body">
    @if (session('status'))
    <div class="alert alert-success" role="alert">
        {{ session('status') }}
    </div>
    @endif

    @foreach($editmember as $row)
    <form action="{{ action('Member1Controller@update', $row->id) }}" method="post">
        {{ csrf_field() }}
        {{ method_field('PATCH') }}
       
        <div class="form-row">
            <div class="col-md-3 mb-4">
                <label for="validationDefault03">E-mail</label>
                <input type="text" class="form-control" name="email" value="{{$row->email}}">
            </div>
            <div class="col-md-2 mb-4">
                <label for="validationDefault04">Password</label>
                <input type="text" class="form-control" name="password" value="{{$row->password}}">
            </div>

        </div>
        <div class=" text-center">
            <button type="submit" class="btn btn-primary " onclick="return confirm('ต้องการแก้ไขข้อมูลใช่ หรือ ไม่')">เพิ่มข้อมูล</button>
        </div>
        <input type="hidden" name="_method" value="PATCH">
    </form>
</div>

@endforeach
@endsection