routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('register2', function () {
    return view('auth.register2');
});

Route::post('regis/insert', 'RegistersController@index');

//student
Route::get('filefull', function () {
    $idu = Auth::user()->id;
    $data['project'] = DB::table('membersprojects')
        ->select('projects_id')
        ->where('students_id', $idu)
        ->get();
    $data['fileproject'] = DB::table('membersprojects')
        ->leftJoin('projects', 'membersprojects.projects_id', 'projects.id')
        ->where('membersprojects.students_id', $idu)
        ->get();
    //dd($data['fileproject']);
    return view('page.student.upFileFull', $data);
});
Route::post('upfilefull/{id}', 'myProjectController@store');
Route::post('Requestexam/{id}', 'RequestexamController@index');
Route::post('Requestexams/addexam', 'RequestexamController@store');
Route::get('menu/project', function () {
    return view('page.student.menuproject');
});
Route::post('studentFileEnd/{id}', 'RequestexamController@updateFileEnd');
Route::post('upstatus_pro2/{id}', 'AdminController@upstatus_exam');

Route::get('exam/show', 'RequestexamController@showexam');
Route::get('exam/showcalendar', 'RequestexamController@showexamcalendar');

Route::get('exam/showstatus', 'RequestexamController@showstatus');

Route::resource('Projectall', 'ProjectallController');
Route::resource('stdinfor', 'StdinformationController');
Route::resource('adviser', 'AdviserController');
Route::resource('myProject', 'myProjectController');

Route::resource('editproject', 'EditProjectController');

Route::get('std1', function () {
    return view('page.student.std1');
});
Route::resource('createProject', 'createProjectController');

Route::get('std5', function () {
    return view('page.student.std5');
});

Route::get('studentHome', function () {
    return view('page.student.studentHome');
});



Route::get('/MidtermExam', function () {
    return view('page/student/MidtermExam');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


//profesors
Route::post('upstatus_adviser/{project_nameth}', 'ConsultantRequestController@upstatus_adviser');
Route::get('detel_adviser/{project_nameth}', 'ConsultantRequestController@detel');
Route::resource('ConsultantRequest', 'ConsultantRequestController');
Route::post('exam/addpoin', 'examofficersController@addpoinofficer');

Route::post('upstatus_studentexam/{project_name}', 'StudentExamOfficerController@upstatus_adviser');
Route::get('detel_studentexam/{project_name}', 'StudentExamOfficerController@detel');
Route::get('examsoff/poin/{exam_id}', 'examofficersController@addpoin');
Route::get('examsoff/poin/show/{id}', 'examofficersController@showpoin');
Route::get('showcalandarexam/{id}', 'ExamController@showcalandarexam');
Route::get('showcalandarexam/officer/{id}', 'examofficersController@showcalandarexam');

Route::resource('StudentExamOfficer', 'StudentExamOfficerController');
Route::resource('examofficers', 'examofficersController');

Route::resource('ListProjectsConsult', 'ListProjectsConsultController');

Route::get('DocumentProjectConsultant', function () {
    return view('page.profesor.DocumentProjectConsultant');
});
Route::get('profesHome', function () {
    return view('page.profesor.profesHome');
});

Route::get('managemember', function () {
    return view('page.profesor.managemember');
});
Route::get('/', function () {
    return view('auth.login');
});
Route::resource('createExam', 'ExamController');
Route::resource('Exam', 'ExamController');




//admin 
Route::post('upstatus_studentexamAD/{project_name}', 'StudentExamAdminController@upstatus_adviser');
Route::get('detel_studentexamAD/{project_name}', 'StudentExamAdminController@detel');
Route::resource('StudentExamAdmin', 'StudentExamAdminController');

Route::post('upstatus_admin/{project_name}', 'ConsultantRequestAdminController@upstatus_admin');
Route::get('detel_admin/{project_name}', 'ConsultantRequestAdminController@detel');
Route::resource('ConsultantRequestAdmin', 'ConsultantRequestAdminController');
Route::patch('Examadminuppoin/{exam_id}', 'ExamadminController@update');

Route::get('detel/{project_name}', 'AdminController@detel');
Route::get('exam/showexam', 'ExamadminController@index');
Route::get('exam/manage/{id}', 'ExamadminController@manage');
Route::delete('exam/editmanage/{id}', 'ExamadminController@destroy');
Route::post('Exam/manage/create', 'ExamadminController@managecreate');
Route::get('examsadmin/poin/{id}', 'ExamadminController@addpoin');
Route::post('examadmin/addpoin', 'ExamadminController@addpoinadmin');
Route::get('examsadmin/poin/show/{id}', 'ExamadminController@showpoin');
Route::get('examsadmin/seccess/{id}', 'ExamadminController@seccess');
Route::get('examsadmin/report/{id}', 'ExamadminController@report');


Route::resource('requesteexam', 'AdminController');
Route::post('upstatus1/{project_name}', 'AdminController@upstatus1');

Route::resource('Adviser', 'AdviserController');

Route::get('/allproject', 'AdminController@allproject')->name('allproject');
Route::get('/allprojectAdmin', 'AdminController@allprojectAdmin')->name('allprojectAdmin');

Route::resource('officer', 'OfficerController');
Route::post('addofficer', 'OfficerController@store');
Route::resource('Addadviser', 'AdviserController');
Route::post('createAdviser', 'AdviserController@store');
Route::resource('project_type', 'ProjecttypesController');

Route::resource('requestexam2', 'RequestexamController');
Route::post('add/status/{id}', 'RequesteexamController@upstatus');
Route::resource('member', 'Member1Controller');

Route::delete('/destroy/{id}', 'Member1Controller@destroy');



Route::get('createmember', function () {
    return view('auth.register');
});

resources/views/Layout/master.blade.php
<!DOCTYPE html>
<html lang="en">


<head>
    <title>@yield('title')</title>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="description">
    <meta content="" name="keywords">

    <link href="{{ asset('img/profile-img.png') }}" rel="icon">
    <link href="{{ asset('img/apple-touch-icon.png') }}" rel="apple-touch-icon">

    <link
        href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
        rel="stylesheet">

    <link href="{{ asset('vendor/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ asset('vendor/icofont/icofont.min.css') }}" rel="stylesheet">
    <link href="{{ asset('vendor/boxicons/css/boxicons.min.css') }}" rel="stylesheet">
    <link href="{{ asset('vendor/venobox/venobox.css') }}" rel="stylesheet">
    <link href="{{ asset('vendor/owl.carousel/assets/owl.carousel.min.css') }}" rel="stylesheet">
    <link href="{{ asset('vendor/aos/aos.css') }}" rel="stylesheet">

    <link href="{{ asset('css/style.css') }}" rel="stylesheet">
    <link href="{{ asset('css/color.css') }}" rel="stylesheet">


    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Kanit:wght@300&family=Sarabun:wght@300;400;500&display=swap"
        rel="stylesheet">



    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">

    <link href="{{ asset('vendor/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">


</head>
<style>
    body {
        /* background-image: url('img/02.jpg'); */
        background-repeat: no-repeat;
        background-attachment: fixed;
        background-size: 100% 100%;
        backdrop-filter: blur(5px);
        background-color: rgba(255, 255, 255, 0.4);
    }
    #i{
        color:rgb(120,132,232);
    }

</style>

<body>

    @include('Layout.sidebar')
    <div style="margin-top: 20px" class="container col-sm-12-mt-0">

        <div class="card shadow" style="background-color: rgb(250,250,250);">


            <div class="card-body row-12">
                @yield('content')

            </div>
        </div>
    </div>

    <!-- End  Footer -->

</body>



<a href="#" class="back-to-top"><i class="icofont-simple-up"></i></a>
@yield('footerscript')
@yield('scripts')
<!-- Vendor JS Files -->
<!-- Template Main JS File -->
{{-- ** --}}
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<link rel="stylesheet"
    href="{{ asset('https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/css/bootstrap-select.css') }}" />
<script src="{{ asset('https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js') }}"></script>
<script src="{{ asset('https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.bundle.min.js') }}"></script>
<script
    src="{{ asset('https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/js/bootstrap-select.min.js') }}">
</script>

{{-- * --}}

<!-- Bootstrap -->

<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"></script>
<!-- jQuery -->
<script src="https://cdn.datatables.net/1.10.23/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.23/js/dataTables.bootstrap4.min.js"></script>
<script type="text/javascript">
    $(document).ready(function() {
        $('#example').DataTable();
        $('select').selectpicker();
        $('#Xselect').selectpicker();
    });

</script>

<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>






<script src="{{ asset('vendor/jquery/jquery.min.js') }}"></script>
<script src="{{ asset('vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
<script src="{{ asset('vendor/jquery.easing/jquery.easing.min.js') }}"></script>
<script src="{{ asset('vendor/php-email-form/validate.js') }}"></script>
<script src="{{ asset('vendor/waypoints/jquery.waypoints.min.js') }}"></script>
<script src="{{ asset('vendor/counterup/counterup.min.js') }}"></script>
<script src="{{ asset('vendor/isotope-layout/isotope.pkgd.min.js') }}"></script>
<script src="{{ asset('vendor/venobox/venobox.min.js') }}"></script>
<script src="{{ asset('vendor/owl.carousel/owl.carousel.min.js') }}"></script>
<script src="{{ asset('vendor/typed.js/typed.min.js') }}"></script>
<script src="{{ asset('vendor/aos/aos.js') }}"></script>

<!-- Template Main JS File -->
<script src="{{ asset('js/main.js') }}"></script>
<script src="{{ asset('js/icon.js') }}"></script>



</html>

resources/views/Layout/masterstd.blade.php
<!DOCTYPE html>
<html lang="en">


<head>
    <title>@yield('title')</title>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="description">
    <meta content="" name="keywords">

    <link href="{{ asset('img/profile-img.png') }}" rel="icon">
    <link href="{{ asset('img/apple-touch-icon.png') }}" rel="apple-touch-icon">

    <link
        href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
        rel="stylesheet">

    <link href="{{ asset('vendor/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ asset('vendor/icofont/icofont.min.css') }}" rel="stylesheet">
    <link href="{{ asset('vendor/boxicons/css/boxicons.min.css') }}" rel="stylesheet">
    <link href="{{ asset('vendor/venobox/venobox.css') }}" rel="stylesheet">
    <link href="{{ asset('vendor/owl.carousel/assets/owl.carousel.min.css') }}" rel="stylesheet">
    <link href="{{ asset('vendor/aos/aos.css') }}" rel="stylesheet">

    <link href="{{ asset('css/style.css') }}" rel="stylesheet">
    <link href="{{ asset('css/color.css') }}" rel="stylesheet">


    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Kanit:wght@300&family=Sarabun:wght@300;400;500&display=swap"
        rel="stylesheet">



    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">

    <link href="{{ asset('vendor/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">


</head>
<style>
    body {
        /* background-image: url('img/02.jpg'); */
        background-repeat: no-repeat;
        background-attachment: fixed;
        background-size: 100% 100%;
        backdrop-filter: blur(5px);
        background-color: rgba(255, 255, 255, 0.4);
    }

</style>

<body>

    @include('Layout.sidebarstd')

    <div style="margin-top: 20px" class="container col-sm-12-mt-0">

        <div class="card shadow" style="background-color: rgb(250,250,250);">


            <div class="card-body row-12">
                @yield('content')

            </div>
        </div>
    </div>

    <!-- End  Footer -->

</body>



<a href="#" class="back-to-top"><i class="icofont-simple-up"></i></a>
@yield('footerscript')
@yield('scripts')
<!-- Vendor JS Files -->
<!-- Template Main JS File -->
{{-- ** --}}
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<link rel="stylesheet"
    href="{{ asset('https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/css/bootstrap-select.css') }}" />
<script src="{{ asset('https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js') }}"></script>
<script src="{{ asset('https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.bundle.min.js') }}"></script>
<script
    src="{{ asset('https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/js/bootstrap-select.min.js') }}">
</script>

{{-- * --}}

<!-- Bootstrap -->
<script src="{{ asset('a/app.js') }}" defer></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"></script>
<!-- jQuery -->
<script src="https://cdn.datatables.net/1.10.23/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.23/js/dataTables.bootstrap4.min.js"></script>
<script type="text/javascript">
    $(document).ready(function() {
        $('#example').DataTable();
        $('select').selectpicker();
        $('#Xselect').selectpicker();

    });

</script>

<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>






<script src="{{ asset('vendor/jquery/jquery.min.js') }}"></script>
<script src="{{ asset('vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
<script src="{{ asset('vendor/jquery.easing/jquery.easing.min.js') }}"></script>
<script src="{{ asset('vendor/php-email-form/validate.js') }}"></script>
<script src="{{ asset('vendor/waypoints/jquery.waypoints.min.js') }}"></script>
<script src="{{ asset('vendor/counterup/counterup.min.js') }}"></script>
<script src="{{ asset('vendor/isotope-layout/isotope.pkgd.min.js') }}"></script>
<script src="{{ asset('vendor/venobox/venobox.min.js') }}"></script>
<script src="{{ asset('vendor/owl.carousel/owl.carousel.min.js') }}"></script>
<script src="{{ asset('vendor/typed.js/typed.min.js') }}"></script>
<script src="{{ asset('vendor/aos/aos.js') }}"></script>

<!-- Template Main JS File -->
<script src="{{ asset('js/main.js') }}"></script>
<script src="{{ asset('js/icon.js') }}"></script>



</html>

resources/views/Layout/sidebar.blade.php
{{--
<link rel="stylesheet" href="{{asset('https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css')}}" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous"> --}}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand">INFORMATION TECHNOLOGY</a>
    <button class="navbar-toggler " type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav mr-auto">

            <li class="nav-item active">
                @if (Auth::user()->type == 'student')
                <a class="nav-link" href={{ url('/menuproject') }}>นิสิต <span class="sr-only">(current)</span></a>
                @elseif(Auth::user()->type == 'admin')
                <a class="nav-link" href={{ url('/profesHome') }}>ADMIN <span class="sr-only">(current)</span></a>
                @elseif(Auth::user()->type == 'officer')
                <a class="nav-link" href={{ url('/profesHome') }}>OFFICER <span class="sr-only">(current)</span></a>
                @endif
            </li>
            @if (Auth::user()->type == 'officer')
            <li class="nav-item">
                <a class="nav-link" href="{{ route('adviser.index') }}">ข้อมูลส่วนตัว</a>
            </li>
            @endif

            @if (Auth::user()->type == 'admin')
            <li class="nav-item">
                <a class="nav-link" href="{{ url('managemember') }}">จัดการสมาชิก</a>
            </li>
            @endif



            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="https://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Settings</a>
                <div class="dropdown-menu" aria-labelledby="dropdown01">
                    <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">ออกจากระบบ</a>

                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                        @csrf
                    </form>
                </div>
            </li>
        </ul>
        {{-- <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form> --}}
    </div>
</nav>


{{-- <script src="{{asset('https://code.jquery.com/jquery-3.3.1.slim.min.js')}}" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="{{asset('https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js')}}" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="{{asset('https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js')}}" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script> --}}

resources/views/Layout/sidebarstd.blade.php
{{--
<link rel="stylesheet" href="{{asset('https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css')}}" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous"> --}}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href={{ url('/profesHome') }}>INFORMATION TECHNOLOGY</a>
    <button class="navbar-toggler " type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav mr-auto">

            <li class="nav-item active">
                <a class="nav-link" href="{{ url('menu/project')}}">STUDENT <span class="sr-only">(current)</span></a>
               
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ route('stdinfor.index')}}">ข้อมูลส่วนตัว</a>
            </li>
            



            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="https://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Settings</a>
                <div class="dropdown-menu" aria-labelledby="dropdown01">
                    <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">ออกจากระบบ</a>

                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                        @csrf
                    </form>
                </div>
            </li>
        </ul>
        {{-- <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form> --}}
    </div>
</nav>


{{-- <script src="{{asset('https://code.jquery.com/jquery-3.3.1.slim.min.js')}}" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="{{asset('https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js')}}" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="{{asset('https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js')}}" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script> --}}