routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('register2', function () {
    return view('auth.register2');
});

Route::post('regis/insert', 'RegistersController@index');

//student
Route::get('filefull', function () {
    $idu = Auth::user()->id;
    $data['project'] = DB::table('membersprojects')
        ->select('projects_id')
        ->where('students_id', $idu)
        ->get();
    $data['fileproject'] = DB::table('membersprojects')
        ->leftJoin('projects', 'membersprojects.projects_id', 'projects.id')
        ->where('membersprojects.students_id', $idu)
        ->get();
    //dd($data['fileproject']);
    return view('page.student.upFileFull', $data);
});
Route::post('upfilefull/{id}', 'myProjectController@store');
Route::post('Requestexam/{id}', 'RequestexamController@index');
Route::post('Requestexams/addexam', 'RequestexamController@store');
Route::get('menu/project', function () {
    return view('page.student.menuproject');
});
Route::post('studentFileEnd/{id}', 'RequestexamController@updateFileEnd');
Route::post('upstatus_pro2/{id}', 'AdminController@upstatus_exam');

Route::get('exam/show', 'RequestexamController@showexam');
Route::get('exam/showcalendar', 'RequestexamController@showexamcalendar');

Route::get('exam/showstatus', 'RequestexamController@showstatus');

Route::resource('Projectall', 'ProjectallController');
Route::resource('stdinfor', 'StdinformationController');
Route::resource('adviser', 'AdviserController');
Route::resource('myProject', 'myProjectController');

Route::resource('editproject', 'EditProjectController');

Route::get('std1', function () {
    return view('page.student.std1');
});
Route::resource('createProject', 'createProjectController');

Route::get('std5', function () {
    return view('page.student.std5');
});

Route::get('studentHome', function () {
    return view('page.student.studentHome');
});



Route::get('/MidtermExam', function () {
    return view('page/student/MidtermExam');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


//profesors
Route::post('upstatus_adviser/{project_nameth}', 'ConsultantRequestController@upstatus_adviser');
Route::get('detel_adviser/{project_nameth}', 'ConsultantRequestController@detel');
Route::resource('ConsultantRequest', 'ConsultantRequestController');
Route::post('exam/addpoin', 'examofficersController@addpoinofficer');

Route::post('upstatus_studentexam/{project_name}', 'StudentExamOfficerController@upstatus_adviser');
Route::get('detel_studentexam/{project_name}', 'StudentExamOfficerController@detel');
Route::get('examsoff/poin/{exam_id}', 'examofficersController@addpoin');
Route::get('examsoff/poin/show/{id}', 'examofficersController@showpoin');
Route::get('showcalandarexam/{id}', 'ExamController@showcalandarexam');
Route::get('showcalandarexam/officer/{id}', 'examofficersController@showcalandarexam');

Route::resource('StudentExamOfficer', 'StudentExamOfficerController');
Route::resource('examofficers', 'examofficersController');

Route::resource('ListProjectsConsult', 'ListProjectsConsultController');

Route::get('DocumentProjectConsultant', function () {
    return view('page.profesor.DocumentProjectConsultant');
});
Route::get('profesHome', function () {
    return view('page.profesor.profesHome');
});

Route::get('managemember', function () {
    return view('page.profesor.managemember');
});
Route::get('/', function () {
    return view('auth.login');
});
Route::resource('createExam', 'ExamController');
Route::resource('Exam', 'ExamController');




//admin 
Route::post('upstatus_studentexamAD/{project_name}', 'StudentExamAdminController@upstatus_adviser');
Route::get('detel_studentexamAD/{project_name}', 'StudentExamAdminController@detel');
Route::resource('StudentExamAdmin', 'StudentExamAdminController');

Route::post('upstatus_admin/{project_name}', 'ConsultantRequestAdminController@upstatus_admin');
Route::get('detel_admin/{project_name}', 'ConsultantRequestAdminController@detel');
Route::resource('ConsultantRequestAdmin', 'ConsultantRequestAdminController');
Route::patch('Examadminuppoin/{exam_id}', 'ExamadminController@update');

Route::get('detel/{project_name}', 'AdminController@detel');
Route::get('exam/showexam', 'ExamadminController@index');
Route::get('exam/manage/{id}', 'ExamadminController@manage');
Route::delete('exam/editmanage/{id}', 'ExamadminController@destroy');
Route::post('Exam/manage/create', 'ExamadminController@managecreate');
Route::get('examsadmin/poin/{id}', 'ExamadminController@addpoin');
Route::post('examadmin/addpoin', 'ExamadminController@addpoinadmin');
Route::get('examsadmin/poin/show/{id}', 'ExamadminController@showpoin');
Route::get('examsadmin/seccess/{id}', 'ExamadminController@seccess');
Route::get('examsadmin/report/{id}', 'ExamadminController@report');


Route::resource('requesteexam', 'AdminController');
Route::post('upstatus1/{project_name}', 'AdminController@upstatus1');

Route::resource('Adviser', 'AdviserController');

Route::get('/allproject', 'AdminController@allproject')->name('allproject');
Route::get('/allprojectAdmin', 'AdminController@allprojectAdmin')->name('allprojectAdmin');

Route::resource('officer', 'OfficerController');
Route::post('addofficer', 'OfficerController@store');
Route::resource('Addadviser', 'AdviserController');
Route::post('createAdviser', 'AdviserController@store');
Route::resource('project_type', 'ProjecttypesController');

Route::resource('requestexam2', 'RequestexamController');
Route::post('add/status/{id}', 'RequesteexamController@upstatus');
Route::resource('member', 'Member1Controller');

Route::delete('/destroy/{id}', 'Member1Controller@destroy');



Route::get('createmember', function () {
    return view('auth.register');
});

resources/views/page/profesor/ConsultantRequest.blade.php
@extends('Layout.master')
@section('title')
คำขอเป็นที่ปรึกษา
@endsection('title')

@section('content')

<div class="section-title">
    <h2>คำขอเป็นที่ปรึกษา</h2>
</div>
<a href="{{ route('ListProjectsConsult.index')}}">
    <button type="button" class="btn btn-info">โปรเจคในที่ปรึกษา</button></a>
<div class="table-responsive"><br>
    <table class="table table-hover">
        <thead>
            <tr>
                <th class="column3">ชื่อโปรเจค</th>
                <th class="column3">รายละเอียดโปรเจ็ค</th>
                <th class="column5">อนุมัติ</th>
                <th class="column6">ไม่อนุมัติ</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($project as $row)
            <tr>
                <td>{{ $row->project_nameth }}</td>
                <td>
                    <a href="{{ url('detel_adviser', $row->project_nameth) }}" type="submit" style='font-size:15px' class="w3-button w3-blue w3-round-xlarge far " method="get">แสดงรายละเอียด</a>
                </td>

                <td class="column5">
                    <form action="{{ url('upstatus_adviser', $row->project_nameth) }}" method="post" enctype="multipart/form-data">
                        {{ csrf_field() }}
                        <button onclick="myFunction()" type="submit" style='font-size:15px' class="w3-button w3-green w3-round-xlarge far " name="status_topic_adviser" value="ผ่านการอนุมัติ">อนุมัติ</button>
                        <script>
                            function myFunction() {
                                alert("You pressed OK!");
                            }
                        </script>
                    </form>
                </td>

                <td class="column6">
                    <button type="button" class="w3-button w3-red w3-round-xlarge far " data-toggle="modal" data-target="#d1">
                        ไม่อนุมัติ
                    </button>
                </td>

            </tr>



            <div class="modal fade" id="d1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered modal-xl">

                    <div class="modal-content">

                        <!-- Modal Header -->
                        <div class="modal-header">
                            <h4 class="" required="">ความคิดเห็น</h4>
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                        </div>
                        <form action="{{ url('upstatus_adviser', $row->project_nameth) }}" method="post" enctype="multipart/form-data">
                            {{ csrf_field() }}

                            <!-- Modal body -->
                            <div class="modal-body">
                                <div class="form-row">
                                    <div class="col-md-12 ">
                                        <input type="hidden" name="status_topic_adviser" value="ไม่ผ่านการอนุมัติ">
                                        <textarea name="detail" class="form-control" id="" cols="30" rows="10"></textarea>
                                    </div>
                                </div>



                            </div>
                            <!-- Modal footer -->
                            <div class="modal-footer">
                                <button type="submit" class="btn btn-primary">save</button>
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            </div>
                        </form>
                    </div>
                </div>

            </div>

        </tbody>
        @endforeach
    </table>

</div>
<br>
<div class="section-title">
    <h2>สถานะโปรเจคขอเป็นที่ปรึกษา</h2>
</div>

<div class="table-responsive">
    <table class="table">
        <thead>
            <tr>
                <th scope="col">ชื่อโปรเจค</th>
                <th scope="col">สถานะอาจารย์ที่ปรึกษา</th>
                <th scope="col">สถานะอาจารย์ประจำวิชา</th>
                <th scope="col">รายละเอียด</th>

            </tr>
        </thead>
        <tbody>
            @foreach($projects as $row)
            <tr>

                <td>{{$row->project_nameth}}</td>
                <td>{{$row->status_topic_adviser}}</td>
                <td>{{$row->status_topic_admin}}</td>
                <td class="column6">
                    <button type="button" class="bx bx-comment-detail  btn btn-primary " data-toggle="modal" data-target="#d2">
                    </button>
                </td>

            </tr>
            <div class="modal fade" id="d2" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered modal-xl">

                    <div class="modal-content">

                        <!-- Modal Header -->
                        <div class="modal-header">
                            <h4>รายละเอียดการสอบ</h4>
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                        </div>

                        <!-- Modal body -->
                        <div class="modal-body">
                            <div class="form-row">
                                <div class="col-md-12 ">
                                <i class="fas fa-align-center"></i>
                                    ระดับโปรเจค -> {{$row->pro1_pro2_status}}<hr><i class="fas fa-align-center"></i>
                                    ชื่อโปรเจค -> {{$row->project_nameth}}<hr><i class="fas fa-align-center"></i>
                                    ชื่อโปรเจค -> {{$row->project_nameen}} <hr><i class="fas fa-align-center"></i>
                                    รายละเอียดโปรเจค -> {{$row->project_detailth}} <hr><i class="fas fa-align-center"></i>
                                    รายละเอียดโปรเจค -> {{$row->project_detailen}}<hr><i class="fas fa-align-center"></i>
                                    สถานะสอบกลางภาค -> {{$row->status_midterm}} <hr><i class="fas fa-align-center"></i>
                                    สถานะสอบปลายภาค -> {{$row->status_final}}
                                </div>
                            </div>

                        </div>
                        <!-- Modal footer -->
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        </div>
                    </div>
                </div>

            </div>
        </tbody>
        @endforeach

    </table>
</div>

@endsection

resources/views/page/profesor/Editadviser.blade.php
@extends('Layout.master')
@section('title')
@endsection('title')
@section('content')
    <div class="section-title">
        <h2>INFORMATION TECHNOLOGY</h2>
        <h4>&nbsp;&nbsp;ข้อมูลส่วนตัว</h4>
    </div>
    <div class="container">
        @foreach ($officer as $row)
            <form action="{{ action('AdviserController@update', $row->id) }}" method="post">
                {{ csrf_field() }}
                {{ method_field('PATCH') }}
                <div class="row">
                    &nbsp;&nbsp;&nbsp;&nbsp;<h4>
                        <p class="font-weight-bold">
                            ชื่อ : <input type="text" name="officer_name" value="{{ $row->officer_name }}">
                            สกุล : <input type="text" name="officer_lastname" value="{{ $row->officer_lastname }}">
                        </p>
                </div>
                <div class="row mt-0">
                    &nbsp;&nbsp;&nbsp;&nbsp;<h4>
                        <p class="font-weight-bold">เบอร์โทรศัพท์ : <input type="text" name="tel_off"
                                value="{{ $row->tel_off }}"></p>

                </div>
                <div class=" text-center">
                    <button type="submit" class="btn btn-primary "
                        onclick="return confirm('ต้องการแก้ไขข้อมูลใช่ หรือ ไม่')">เพิ่มข้อมูล</button>
                </div>
                <input type="hidden" name="_method" value="PATCH">
            </form>
        @endforeach
    </div>

@endsection

resources/views/page/profesor/ListProjectsConsult.blade.php
@extends('Layout.master')
@section('title')
โปรเจคในที่ปรึกษา
@endsection('title')

@section('content')


<!-- ======= Portfolio Section ======= -->


<div class="section-title">
    <h2>รายชื่อโปรเจคในที่ปรึกษา</h2>
</div>


<div class="table-responsive">
    <table class="table">
        <thead>
            <tr>
                <th scope="col">ชื่อโปรเจค</th>
                <th scope="col">รายละเอียด</th>

            </tr>
        </thead>
        <tbody>
            @foreach($project as $row)
            <tr>

                <td>{{$row->project_nameth}}</td>

                <td class="column6">
                    <button type="button" class="bx bx-comment-detail  btn btn-primary " data-toggle="modal" data-target="#d1">
                    </button>
                </td>



            </tr>


            <div class="modal fade" id="d1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered modal-xl">

                    <div class="modal-content">

                        <!-- Modal Header -->
                        <div class="modal-header">
                            <h4>รายละเอียดการสอบ</h4>
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                        </div>

                        <!-- Modal body -->
                        <div class="modal-body">
                            <div class="form-row">
                                <div class="col-md-12 ">
                                    <i class="fas fa-align-center"></i>
                                    ระดับโปรเจค -> {{$row->pro1_pro2_status}}
                                    <hr><i class="fas fa-align-center"></i>
                                    สถานะจบ/ไม่จบ -> {{$row->status_finished_notfinished}}
                                    <hr><i class="fas fa-align-center"></i>
                                    ชื่อโปรเจค -> {{$row->project_nameth}}
                                </div>
                            </div>

                        </div>
                        <!-- Modal footer -->
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        </div>
                    </div>
                </div>

            </div>


        </tbody>
        @endforeach

    </table>



    @endsection

resources/views/page/profesor/StudentExamOfficer.blade.php
@extends('Layout.master')
@section('title')
คำขอขึ้นสอบ
@endsection('title')

@section('content')

<div class="section-title">
    <h2>คำขอขึ้นสอบ</h2>
</div>
<table class="table table-hover">
    <thead>
        <tr>
            <th class="column3">ชื่อโปรเจ็ค</th>
            <th class="column3">ปีการศึกษา</th>
            <th class="column3">รายละเอียดโปรเจ็ค</th>
            <th class="column5">อนุมัติ</th>
            <th class="column6">ไม่อนุมัติ</th>
        </tr>
    </thead>
    <tbody>
        @foreach ($studentexamofficer as $row)
        <tr>
            <td>{{ $row->project_nameth }}</td>
            <td>{{ $row->yearedu }}</td>
            <td>
                <a href="{{ url('detel_studentexam', $row->project_nameth) }}" type="submit" style='font-size:15px' class="w3-button w3-blue w3-round-xlarge far " method="get">แสดงรายละเอียด</a>
            </td>

            <td class="column5">
                <form action="{{ url('upstatus_studentexam', $row->id) }}" method="post" enctype="multipart/form-data">
                    {{ csrf_field() }}
                    <button onclick="myFunction()" type="submit" style='font-size:15px' class="w3-button w3-green w3-round-xlarge far " name="status_exam_adviser" value="ผ่านการอนุมัติ">อนุมัติ</button>
                    <script>
                        function myFunction() {
                            alert("You pressed OK!");
                        }
                    </script>
                </form>
            </td>

            <td class="column6">
                <button type="button" class="w3-button w3-red w3-round-xlarge far " data-toggle="modal" data-target="#d1">
                    ไม่อนุมัติ
                </button>
            </td>

        </tr>



        <div class="modal fade" id="d1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered modal-xl">

                <div class="modal-content">

                    <!-- Modal Header -->
                    <div class="modal-header">
                        <h4 class="" required="">ความคิดเห็น</h4>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>
                    <form action="{{ url('upstatus_studentexam', $row->id) }}" method="post" enctype="multipart/form-data">
                        {{ csrf_field() }}

                        <!-- Modal body -->
                        <div class="modal-body">
                            <div class="form-row">
                                <div class="col-md-12 ">
                                    <input type="hidden" name="status_exam_adviser" value="ไม่ผ่านการอนุมัติ">
                                    <textarea name="detail" class="form-control" id="" cols="30" rows="10"></textarea>
                                </div>
                            </div>



                        </div>
                        <!-- Modal footer -->
                        <div class="modal-footer">
                            <button type="submit" class="btn btn-primary">save</button>
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        </div>
                    </form>
                </div>
            </div>

        </div>

    </tbody>
    @endforeach
</table>

@endsection

resources/views/page/profesor/adviserInfor.blade.php
@extends('Layout.master')
@section('title')
@endsection('title')
@section('content')
<div class="section-title">
    <h2>INFORMATION TECHNOLOGY</h2>
    <h4>&nbsp;&nbsp;ข้อมูลส่วนตัว</h4>
</div>

@foreach($officer as $row)
    <div class="row">
        &nbsp;&nbsp;&nbsp;&nbsp;<h4>
            <p class="font-weight-bold">ชื่อ :</p>
        </h4>&nbsp;<h4>{{$row->officer_name}}&nbsp;&nbsp;{{$row->officer_lastname}}</h4>
    </div>
    {{-- <div class="row mt-0">
        &nbsp;&nbsp;&nbsp;&nbsp;<h4>
            <p class="font-weight-bold">รหัสนิสิต :</p>
        </h4>&nbsp;<h4>{{$row->student_id}}</h4>
    </div> --}}
    <div class="row mt-0">
        &nbsp;&nbsp;&nbsp;&nbsp;<h4>
            <p class="font-weight-bold">เบอร์โทรศัพท์ :</p>
        </h4>&nbsp;<h4>{{$row->tel_off}}</h4>
    </div>
    <a href="{{ action('AdviserController@edit', $row->id) }}" class="btn btn-warning"><i class="fa fa-wrench"></i></a>
    @endforeach


@endsection

resources/views/page/profesor/managemember.blade.php
@extends('Layout.master')
@section('title')
หน้าแรก
@endsection('title')

@section('content')

<div class="section-title">
    <h2>INFORMATION TECHNOLOGY</h2>
</div>

<div class="w3-row-padding w3-padding-64 w3-theme-l1" id="work">

    <div class="w3-quarter">
        <div class="w3-card w3-white">
            <div class="w3-container">
                <dt class="card-title mt-3"> จัดการอาจารย์</dt>
                <p class="card-text" style=" color: rgb(100,100,100);">เพิ่ม ลบ แก้ไข อาจารย์</p>
            </div>
            <div class="col-4">
                <a href="{{ route('officer.index') }}">
                    <i class="bx bx-user-plus" style="font-size: 70px; color: rgb(120,132,232);"></i>
                </a>
            </div>
        </div>
    </div>



    <div class="w3-quarter">
        <div class="w3-card w3-white">
            <div class="w3-container">
                <dt class="card-title mt-3">จัดการนิสิต</dt>
                <p class="card-text" style=" color: rgb(100,100,100);">เพิ่ม ลบ แก้ไข นิสิต</p>
            </div>
            <div class="col-4">
                <a href="{{ route('member.index') }}">
                    <i class="bx bx-bot" style="font-size: 70px; color: rgb(120,132,232);"></i>
                </a>
            </div>
        </div>
    </div>


</div>


@endsection

resources/views/page/profesor/profesHome.blade.php
@extends('Layout.master')
@section('title')
หน้าแรก
@endsection('title')

@section('content')
<div class="section-title">
    <h2>INFORMATION TECHNOLOGY</h2>
</div>
<div class="w3-row-padding w3-padding-64 w3-theme-l1" id="work">

    @if(Auth::user()->type == 'officer')
    <div class="w3-quarter">
        <div class="w3-card w3-white">
            <div class="w3-container">
                <dt class="card-title mt-3"> คำร้องขอเป็นที่ปรึกษา</dt>
                <p class="card-text" style=" color: rgb(100,100,100);">อนุมัติคำร้อง <br> ที่ขอเป็นโปรเจคในที่ปรึกษา</p>

                <a href="{{ url('/ConsultantRequest') }}">
                    <i class="bx bx-face" style="font-size: 70px; color: rgb(120,132,232);"></i>
                </a>

            </div>
        </div>
    </div>

    <div class="w3-quarter">
        <div class="w3-card w3-white">
            <div class="w3-container">
                <dt class="card-title mt-3">คำร้องขอขึ้นสอบ</dt>
                <p class="card-text" style=" color: rgb(100,100,100);">อนุมัติคำร้อง <br> โปรเจคที่ขอขึ้นสอบ</p>

                <a href="{{ url('/StudentExamOfficer') }}">
                    <i class="bx bx-book-add" style="font-size: 70px; color: rgb(120,132,232);"></i>
                </a>

            </div>
        </div>
    </div>
    <div class="w3-quarter">
        <div class="w3-card w3-white">
            <div class="w3-container">
                <dt class="card-title mt-3">โปรเจคทั้งหมด</dt>
                <p class="card-text" style=" color: rgb(100,100,100);">ดูโปรเจคทั้งหมด
                    ที่มีในระบบ</p>

                <a href="{{ url('/allproject') }}" type="text">
                    <i class="bx bx-layer" style="font-size: 70px; color: rgb(120,132,232);"></i>
                </a>

            </div>
        </div>
    </div>
    <div class="w3-quarter">
        <div class="w3-card w3-white">
            <div class="w3-container">
                <dt class="card-title mt-3">สอบ</dt>
                <p class="card-text" style=" color: rgb(100,100,100);">แสดงหรือให้คะแนนสอบ <br> ที่เปิดทำการสอบ</p>

                <a href="{{route('examofficers.index')}}" type="text">
                    <i class="bx bx-bot" style="font-size: 70px; color: rgb(120,132,232);"></i>
                </a>

            </div>
        </div>
    </div>

    @elseif(Auth::user()->type == 'admin')
    <div class="w3-quarter">
        <div class="w3-card w3-white">
            <div class="w3-container">
                <dt class="card-title mt-3"> อนุมัติหัวข้อโปรเจค</dt>
                <p class="card-text" style=" color: rgb(100,100,100);">อนุมัติคำร้อง <br> ที่ขอสร้างหัวข้อโปรเจค</p>

                <a href="{{ route('ConsultantRequestAdmin.index') }}">
                    <i class="bx bx-face" style="font-size: 70px; color: rgb(120,132,232);"></i>
                </a>
            </div>
        </div>
    </div>

    <div class="w3-quarter">
        <div class="w3-card w3-white">
            <div class="w3-container">
                <dt class="card-title mt-3">คำร้องขอขึ้นสอบ</dt>
                <p class="card-text" style=" color: rgb(100,100,100);">อนุมัติคำร้อง <br> โปรเจคที่ขอขึ้นสอบ</p>

                <a href="{{ url('/StudentExamAdmin') }}">
                    <i class="bx bx-book-add" style="font-size: 70px; color: rgb(120,132,232);"></i>
                </a>
            </div>
        </div>
    </div>


    <div class="w3-quarter">
        <div class="w3-card w3-white">
            <div class="w3-container">
                <dt class="card-title mt-3"> เพิ่มประเภทโปรเจค</dt>
                <p class="card-text" style=" color: rgb(100,100,100);">เพิ่มประเภทของโปรเจคและอาจารย์ประจำประเภทโปรเจค</p>

                <a href="{{ route('project_type.index') }}" type="text">
                    <i class="bx bx-list-ol" style="font-size: 70px; color: rgb(120,132,232);"></i>
                </a>
            </div>
        </div>
    </div>



    <div class="w3-quarter">
        <div class="w3-card w3-white">
            <div class="w3-container">
                <dt class="card-title mt-3">จัดการสอบ</dt>
                <p class="card-text" style=" color: rgb(100,100,100);">สร้าง ลบ แก้ไขการสอบต่างๆ เพื่อให้นิสิตทำการยื่นขอสอบ
                </p>
            
                <a href="{{ route('Exam.index') }}" type="text">
                    <i class="bx bx-layer" style="font-size: 70px; color: rgb(120,132,232);"></i>
                </a>
            </div>
        </div>
    </div>


    <div style="margin-top: 100px;" class="w3-quarter">
        <div class="w3-card w3-white">
            <div class="w3-container">

                <dt class="card-title mt-3">สอบ</dt>
                <p class="card-text" style=" color: rgb(100,100,100);">แสดงหรือให้คะแนนสอบ <br> ที่เปิดทำการสอบ</p>
            </div>
            <div class="col-4">
                <a href="{{url('exam/showexam')}}" type="text">
                    <i class="bx bx-bot" style="font-size: 70px; color: rgb(120,132,232);"></i>
                </a>
            </div>
        </div>
    </div>
    <div style="margin-top: 100px;" class="w3-quarter">
        <div class="w3-card w3-white">
            <div class="w3-container">
                <dt class="card-title mt-3">โปรเจคทั้งหมด</dt>
                <p class="card-text" style=" color: rgb(100,100,100);">ดูโปรเจคทั้งหมด
                    ที่มีในระบบ</p>

                <a href="{{ url('/allprojectAdmin') }}" type="text">
                    <i class="bx bx-layer" style="font-size: 70px; color: rgb(120,132,232);"></i>
                </a>

            </div>
        </div>
    </div>
</div>

@endif
@endsection