routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('register2', function () {
    return view('auth.register2');
});

Route::post('regis/insert', 'RegistersController@index');

//student
Route::get('filefull', function () {
    $idu = Auth::user()->id;
    $data['project'] = DB::table('membersprojects')
        ->select('projects_id')
        ->where('students_id', $idu)
        ->get();
    $data['fileproject'] = DB::table('membersprojects')
        ->leftJoin('projects', 'membersprojects.projects_id', 'projects.id')
        ->where('membersprojects.students_id', $idu)
        ->get();
    //dd($data['fileproject']);
    return view('page.student.upFileFull', $data);
});
Route::post('upfilefull/{id}', 'myProjectController@store');
Route::post('Requestexam/{id}', 'RequestexamController@index');
Route::post('Requestexams/addexam', 'RequestexamController@store');
Route::get('menu/project', function () {
    return view('page.student.menuproject');
});
Route::post('studentFileEnd/{id}', 'RequestexamController@updateFileEnd');
Route::post('upstatus_pro2/{id}', 'AdminController@upstatus_exam');

Route::get('exam/show', 'RequestexamController@showexam');
Route::get('exam/showcalendar', 'RequestexamController@showexamcalendar');

Route::get('exam/showstatus', 'RequestexamController@showstatus');

Route::resource('Projectall', 'ProjectallController');
Route::resource('stdinfor', 'StdinformationController');
Route::resource('adviser', 'AdviserController');
Route::resource('myProject', 'myProjectController');

Route::resource('editproject', 'EditProjectController');

Route::get('std1', function () {
    return view('page.student.std1');
});
Route::resource('createProject', 'createProjectController');

Route::get('std5', function () {
    return view('page.student.std5');
});

Route::get('studentHome', function () {
    return view('page.student.studentHome');
});



Route::get('/MidtermExam', function () {
    return view('page/student/MidtermExam');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


//profesors
Route::post('upstatus_adviser/{project_nameth}', 'ConsultantRequestController@upstatus_adviser');
Route::get('detel_adviser/{project_nameth}', 'ConsultantRequestController@detel');
Route::resource('ConsultantRequest', 'ConsultantRequestController');
Route::post('exam/addpoin', 'examofficersController@addpoinofficer');

Route::post('upstatus_studentexam/{project_name}', 'StudentExamOfficerController@upstatus_adviser');
Route::get('detel_studentexam/{project_name}', 'StudentExamOfficerController@detel');
Route::get('examsoff/poin/{exam_id}', 'examofficersController@addpoin');
Route::get('examsoff/poin/show/{id}', 'examofficersController@showpoin');
Route::get('showcalandarexam/{id}', 'ExamController@showcalandarexam');
Route::get('showcalandarexam/officer/{id}', 'examofficersController@showcalandarexam');

Route::resource('StudentExamOfficer', 'StudentExamOfficerController');
Route::resource('examofficers', 'examofficersController');

Route::resource('ListProjectsConsult', 'ListProjectsConsultController');

Route::get('DocumentProjectConsultant', function () {
    return view('page.profesor.DocumentProjectConsultant');
});
Route::get('profesHome', function () {
    return view('page.profesor.profesHome');
});

Route::get('managemember', function () {
    return view('page.profesor.managemember');
});
Route::get('/', function () {
    return view('auth.login');
});
Route::resource('createExam', 'ExamController');
Route::resource('Exam', 'ExamController');




//admin 
Route::post('upstatus_studentexamAD/{project_name}', 'StudentExamAdminController@upstatus_adviser');
Route::get('detel_studentexamAD/{project_name}', 'StudentExamAdminController@detel');
Route::resource('StudentExamAdmin', 'StudentExamAdminController');

Route::post('upstatus_admin/{project_name}', 'ConsultantRequestAdminController@upstatus_admin');
Route::get('detel_admin/{project_name}', 'ConsultantRequestAdminController@detel');
Route::resource('ConsultantRequestAdmin', 'ConsultantRequestAdminController');
Route::patch('Examadminuppoin/{exam_id}', 'ExamadminController@update');

Route::get('detel/{project_name}', 'AdminController@detel');
Route::get('exam/showexam', 'ExamadminController@index');
Route::get('exam/manage/{id}', 'ExamadminController@manage');
Route::delete('exam/editmanage/{id}', 'ExamadminController@destroy');
Route::post('Exam/manage/create', 'ExamadminController@managecreate');
Route::get('examsadmin/poin/{id}', 'ExamadminController@addpoin');
Route::post('examadmin/addpoin', 'ExamadminController@addpoinadmin');
Route::get('examsadmin/poin/show/{id}', 'ExamadminController@showpoin');
Route::get('examsadmin/seccess/{id}', 'ExamadminController@seccess');
Route::get('examsadmin/report/{id}', 'ExamadminController@report');


Route::resource('requesteexam', 'AdminController');
Route::post('upstatus1/{project_name}', 'AdminController@upstatus1');

Route::resource('Adviser', 'AdviserController');

Route::get('/allproject', 'AdminController@allproject')->name('allproject');
Route::get('/allprojectAdmin', 'AdminController@allprojectAdmin')->name('allprojectAdmin');

Route::resource('officer', 'OfficerController');
Route::post('addofficer', 'OfficerController@store');
Route::resource('Addadviser', 'AdviserController');
Route::post('createAdviser', 'AdviserController@store');
Route::resource('project_type', 'ProjecttypesController');

Route::resource('requestexam2', 'RequestexamController');
Route::post('add/status/{id}', 'RequesteexamController@upstatus');
Route::resource('member', 'Member1Controller');

Route::delete('/destroy/{id}', 'Member1Controller@destroy');



Route::get('createmember', function () {
    return view('auth.register');
});

app/Student.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Student extends Model
{
  protected $fillable = [
    
    'student_id',
    'student_name',
    'student_lastname',
    'tel_std',
    'user_id',
  ];
  protected $primaryKey = 'id';
  protected $table = 'Students';
}

resources/views/page/student/EditProject.blade.php
@extends('Layout.masterstd')
@section('title')
@endsection('title')
@section('content')




<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">แก้ไขโปรเจ็ค</div>
                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    <form action="{{action('EditProjectController@update',$editproject->id)}}" method="post">
                        {{ csrf_field() }}
                        {{ method_field('PATCH') }}
                        <div class="form-row">
                            <div class="form-group col-md-4">
                                <label for="inputPassword4">รหัสระบบ</label>
                            <input type="text" class="form-control" name="education_id" value="{{$editproject->education_id}}">
                            </div>
                            <div class="form-group col-md-4">
                                <label for="inputPassword4">ระบบ</label>
                            <input type="text" class="form-control" name="education_name" value="{{$editproject->education_name}}">
                            </div>
                        </div>
                        <div class=" text-center">
                            <button type="submit" class="btn btn-primary " onclick="return confirm('ต้องการแก้ไขข้อมูลใช่ หรือ ไม่')">เพิ่มข้อมูล</button>
                        </div>
                        <input type="hidden" name="_method" value="PATCH">
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/page/student/EditRequestexam.blade.php
@extends('Layout.masterstd')
@section('title')
แก้ไขรายละเอียดการสอบ
@endsection('title')
@section('content')
<div class="section-title">
    <h2>INFORMATION TECHNOLOGY</h2>
    <h3 style="font-family: 'Sarabun', sans-serif;">ยื่นขอสอบ</h3>
    <h3 style="font-family: 'Sarabun', sans-serif;">รายละเอียดการสอบ</h3>
    @foreach ($exams as $exam)
    <h3 style="font-family: 'Sarabun', sans-serif;">&nbsp;&nbsp;<i class=" bx bx-right-arrow-alt"></i> @if($exam -> topic == 'midterm')สอบกลางภาค @elseif($exam -> topic == 'final')สอบปลายภาค @endif ปีการศึกษา {{$exam -> yearedu}}</h3>
    <h3 style="font-family: 'Sarabun', sans-serif;">&nbsp;&nbsp;<i class=" bx bx-right-arrow-alt"></i> @if($exam -> typeproject == 'Project1')โปรเจค1 @elseif($exam -> topic == 'Project2')โปรเจค2 @endif </h3>
    <h3 style="font-family: 'Sarabun', sans-serif;">&nbsp;&nbsp;<i class=" bx bx-calendar"></i>&nbsp;เริ่มสอบวันที่ {{ $exam -> dateexamstart}} ถึง {{$exam -> dateexamend}}</h3>
    <h3 style="font-family: 'Sarabun', sans-serif;">&nbsp;&nbsp;<i class=" bx bx-calendar"></i>&nbsp;เริ่มยื่นขอสอบวันที่ {{ $exam -> dateregisstart}} ถึง {{$exam -> dateregisend}}</h3>
    <h4 style="font-family: 'Sarabun', sans-serif;">&nbsp;&nbsp;&nbsp; {{ $exam -> detail}}</h4>

    <form action="{{action('RequestexamController@update',$exam->id)}}" method="post">
        {{ csrf_field() }}
        {{ method_field('PATCH') }}
        @foreach ($projects as $project)
        <input type="hidden" class="form-control" name="project_id" value="{{ $project -> id}}">
        @endforeach
        <input type="hidden" class="form-control" name="exam_id" value="{{ $exam -> id}}">
        <input type="hidden" class="form-control" name="status_exam_adviser" value="รอการอนุมัติ">
        <input type="hidden" class="form-control" name="status_exam_admin" value="รอการอนุมัติ">
        <hr>
        <div class="form-group col-8">
            <h4 for="exampleFormControlSelect1" style="font-family: 'Sarabun', sans-serif;">เลือกโปรเจค</h4>
            <select class="form-control" id="exampleFormControlSelect1" name="project_id" required="">
                @foreach ($projects as $pro)
                <option value="{{$pro->id}}">{{$pro->project_nameth}}</option>
                @endforeach
            </select>
        </div>

        <div class="form-group col-7">

            <input type="file" name="file_name" class="custom-file-input" id="inputGroupFile01" required="">
            <label class="custom-file-label" for="inputGroupFile01">แนบไฟล์</label>

        </div>

        <div class=" text-center">
            <button type="submit" class="btn btn-primary " onclick="return confirm('ต้องการเพิ่มข้อมูลใช่ หรือ ไม่')"><i class="bx bx-plus-circle">ยื่นขอสอบ</i></button>
        </div>
    </form>
    @endforeach
</div>


@endsection

resources/views/page/student/EditstdInfor.blade.php
@extends('Layout.masterstd')
@section('title')
@endsection('title')
@section('content')
    <div class="section-title">
        <h2>INFORMATION TECHNOLOGY</h2>
        <h4>&nbsp;&nbsp;ข้อมูลส่วนตัว</h4>
    </div>
    <div class="container">
        @foreach ($students as $row)
        <form action="{{ action('StdinformationController@update', $row->id) }}" method="post">
            {{ csrf_field() }}
            {{ method_field('PATCH') }}
            <div class="row">
                &nbsp;&nbsp;&nbsp;&nbsp;<h4>
                    <p class="font-weight-bold">ชื่อ : <input type="text" name="student_name" value="{{ $row->student_name }}">
                       สกุล : <input type="text" name="student_lastname" value="{{ $row->student_lastname }}"></p>
                    

              
            </div>
            <div class="row mt-0">
                &nbsp;&nbsp;&nbsp;&nbsp;<h4>
                    <p class="font-weight-bold">รหัสนิสิต :  <input type="text" name="student_id" value="{{ $row->student_id }}"></p>
                   
               
            </div>
            <div class="row mt-0">
                &nbsp;&nbsp;&nbsp;&nbsp;<h4>
                    <p class="font-weight-bold">เบอร์โทรศัพท์ :  <input type="text" name="tel_std" value="{{ $row->tel_std }}"></p>
                   

                
            </div>
           
                <div class=" text-center">
                    <button type="submit" class="btn btn-primary "
                        onclick="return confirm('ต้องการแก้ไขข้อมูลใช่ หรือ ไม่')">เพิ่มข้อมูล</button>
                </div>
                <input type="hidden" name="_method" value="PATCH">
            </form>
        @endforeach
    </div>

@endsection

resources/views/page/student/Projectall.blade.php
@extends('Layout.masterstd')
@section('title')
@endsection('title')
@section('content')
<div class="section-title">
    <h2>INFORMATION TECHNOLOGY</h2>
    <h4>&nbsp;&nbsp;โปรเจคทั้งหมด</h4>
</div>
<div class="container">
    <table class="table">
        <thead>
            <tr>
                <th scope="col">ลำดับ</th>
                <th scope="col">ชื่อโปรเจค</th>
                <th scope="col">รายละเอียด</th>

            </tr>
        </thead>
        <tbody>
            @foreach ($membersprojects as $row)
            <tr>

                <td></td>
                <td>{{ $row->project_nameth }}</td>
                <td class="column6">
                    <button type="button" class="bx bx-comment-detail  btn btn-primary " data-toggle="modal" data-target="#d1">
                    </button>
                </td>
                <!-- <td>
                                        <center><a href="" class="btn btn-warning">แก้ไข</a></center>
                                    </td>
                                    <td>
                                        <center>
                                            <form action="" method="post">
                                                @csrf
                                                @method('DELETE')
                                                <button type="submit" class="btn btn-danger">ลบ</button>

                                            </form>
                                        </center>
                                    </td> -->
            </tr>

            <div class="modal fade" id="d1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered modal-xl">

                    <div class="modal-content">

                        <!-- Modal Header -->
                        <div class="modal-header">
                            <h4>รายละเอียดการสอบ</h4>
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                        </div>

                        <!-- Modal body -->
                        <div class="modal-body">
                            <div class="form-row">
                                <div class="col-md-12 ">
                                    <i class="fas fa-align-center"></i>
                                    ชื่อโปรเจ็คไทย -> {{$row->project_nameth}}
                                    <hr><i class="fas fa-align-center"></i>
                                    ชื่อโปรเจ็คอังกฤษ -> {{$row->project_nameen}}
                                    <hr><i class="fas fa-align-center"></i>
                                    สถานะหัวข้ออาจารย์ที่ปรึกษา -> {{$row->status_topic_adviser}}
                                    <hr><i class="fas fa-align-center"></i>
                                    สถานะหัวข้อที่อาจารย์ประจำวิชา -> {{$row->status_topic_admin}}
                                </div>
                            </div>

                        </div>
                        <!-- Modal footer -->
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        </div>
                    </div>
                </div>

            </div>




        </tbody>
        @endforeach
    </table>
</div>
<style type="text/css">
    table tr {
        counter-increment: row-num;
    }

    table tr td:first-child::before {
        content: counter(row-num) ". ";
    }
</style>


@endsection

resources/views/page/student/createProject.blade.php
@extends('Layout.masterstd')
@section('title')
@endsection('title')
@section('content')
<div class="section-title">
    <h2>INFORMATION TECHNOLOGY</h2>
    <h4>&nbsp;&nbsp;สร้างโปรเจค</h4>
</div>
<div class="container">
    @if (session('status'))
    <div class="alert alert-success" role="alert">
        {{ session('status') }}
    </div>
    @endif
    <form action="{{ route('createProject.store') }}" method="post">
        {{ csrf_field() }}
        <div class="form">
            <input type="hidden" class="form-control" name="status_topic_adviser" value="รอการอนุมัติ">
            <input type="hidden" class="form-control" name="status_topic_admin" value="รอการอนุมัติ">
            <div class="row">
                <div class="form-group col-md-4">
                    <label for="inputPassword4">โปรเจค</label>
                    <select class="form-control" name="pro1_pro2_status" required="">
                        <option selected value="">เลือก.Pro1,Pro2</option>
                        <option value="Project1">Project1</option>
                        <option value="Project1">Project2</option>
                    </select>
                </div>
                <div class="form-group col-md-4">
                    <label for="inputPassword4">ประเภทโปรเจค</label>
                    <select class="form-control" name="projecttype_id" required="">
                        @foreach ($project_types as $p)
                        <option value="{{ $p->id }}">{{ $p->projecttype_detail }}

                        </option>
                        @endforeach
                    </select>
                </div>
            </div>

            <div class="row">
                <div class="form-group col-md-5">
                    <label for="inputPassword4">สมาชิก</label>
                    <select class="form-control selectpicker" name="students_id[]" multiple data-live-search="true" required="">
                        @foreach ($students as $s)
                        <option value="{{ $s->id }}">{{ $s->student_name }}
                            {{ $s->student_lastname }}
                        </option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group col-md-5">
                    <label for="inputPassword4">ที่ปรึกษา</label>
                    <select name="officer_id[]" id="Xselect" class="form-control selectpicker" multiple data-live-search="true" required="">
                        @foreach ($officer as $s)
                        <option value="{{ $s->id }}">{{ $s->officer_name }} {{ $s->officer_lastname }}
                        </option>
                        @endforeach
                    </select>
                </div>

            </div>
            <div class="row">
                <div class="form-group  col-md-5">
                    <label for="inputPassword4">ชื่อโปรเจค(ไทย)</label>
                    <input type="text" class="form-control" name="project_nameth" required="">
                </div>
                <div class="form-group  col-md-5">
                    <label for="inputPassword4">ชื่อโปรเจค(อังกฤษ)</label>
                    <input type="text" class="form-control" name="project_nameen" required="">
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-8">
                    <label for="inputPassword10">รายละเอียดโปรเจค(ไทย)</label>
                    <textarea class="form-control" rows="7" id="comment" name="project_detailth" required=""></textarea>
                </div>
                <div class="form-group col-md-8">
                    <label for="inputPassword10">รายละเอียดโปรเจค(อังกฤษ)</label>
                    <textarea class="form-control" rows="7" id="comment" name="project_detailen" required=""></textarea>
                </div>
            </div>
        </div>

        <div class=" text-center">
            <button type="submit" class="btn btn-primary " onclick="return confirm('ต้องการสร้างใช่ หรือ ไม่')"><i class="bx bx-plus-circle">สร้างโปรเจค</i></button>
        </div>
    </form>
</div>







@endsection

resources/views/page/student/editstatusproject.blade.php
@extends('Layout.masterstd')
@section('title')
@endsection('title')
@section('content')
<div class="section-title">
    <h2>INFORMATION TECHNOLOGY</h2>
    <h4>&nbsp;&nbsp;สร้างโปรเจค</h4>
</div>
<div class="container">
    @if (session('status'))
    <div class="alert alert-success" role="alert">
        {{ session('status') }}
    </div>
    @endif
    @foreach($Editmembersprojects as $row)
    <form action="{{action('myProjectController@update',$row->id)}}" method="post">
        {{ csrf_field() }}
        {{ method_field('PATCH') }}
        <div class="form">
            <input type="hidden" class="form-control" name="status_topic_adviser" value="รอการอนุมัติ">
            <input type="hidden" class="form-control" name="status_topic_admin" value="รอการอนุมัติ">
            <div class="row">
                <div class="form-group col-md-4">
                    <label for="inputPassword4">โปรเจค : {{$row->pro1_pro2_status}}</label>
                    
                </div>
                
                <div class="form-group col-md-4">
                @foreach ($myproject_types as $p)
                    <label for="inputPassword4">ประเภทโปรเจค : {{$p->projecttype_name}}</label>
                        @endforeach
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-4">
                @foreach ($officer as $of)
                    <label for="inputPassword4">อาจารย์ที่ปรึกษา : {{$of->officer_name}} {{$of->officer_lastname}}</label>
                        @endforeach
                </div>
                
                <div class="form-group col-md-4">
                @foreach ($mystudents as $p)
                    <label for="inputPassword4">ชื่อสมาชิก : {{$p->student_name}} {{$p->student_lastname}}</label>
                        @endforeach
                </div>
            </div>

            
            <div class="row">
                <div class="form-group  col-md-5">
                    <label for="inputPassword4">ชื่อโปรเจค(ไทย)</label>
                    <input type="text" class="form-control" name="project_nameth" value="{{ $row->project_nameth }}" required="">
                </div>
                <div class="form-group  col-md-5">
                    <label for="inputPassword4">ชื่อโปรเจค(อังกฤษ)</label>
                    <input type="text" class="form-control" name="project_nameen" value="{{ $row->project_nameen }}" required="">
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-8">
                    <label for="inputPassword10">รายละเอียดโปรเจค(ไทย)</label>
                    <textarea class="form-control" rows="7" id="comment" name="project_detailth" required="">{{ $row->project_detailth }}</textarea>
                </div>
                <div class="form-group col-md-8">
                    <label for="inputPassword10">รายละเอียดโปรเจค(อังกฤษ)</label>
                    <textarea class="form-control" rows="7" id="comment" name="project_detailen" required="">{{ $row->project_detailen }}</textarea>
                </div>
            </div>
        </div>

        <div class=" text-center">
            <button type="submit" class="btn btn-primary " onclick="return confirm('ต้องการเพิ่มข้อมูลใช่ หรือ ไม่')"><i class="bx bx-plus-circle">เพิ่มข้อมูล</i></button>
        </div>
    </form>
    @endforeach
</div>


<link rel="stylesheet" href="{{ asset('https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/css/bootstrap-select.css') }}" />
<script src="{{ asset('https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js') }}"></script>
<script src="{{ asset('https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.bundle.min.js') }}"></script>
<script src="{{ asset('https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/js/bootstrap-select.min.js') }}">
</script>


<script>
    $('select').selectpicker();
    $('#Xselect').selectpicker();
</script>





@endsection

resources/views/page/student/menuproject.blade.php
@extends('Layout.masterstd')
@section('title')
@endsection('title')

@section('content')

<div class="section-title">
    <h2>INFORMATION TECHNOLOGY</h2>
</div>

<div class="w3-row-padding w3-padding-64 w3-theme-l1" id="work">

    <div class="w3-quarter">
        <div class="w3-card w3-white">
            <div class="w3-container">
                <dt class="card-title mt-3"> สร้างโปรเจค</dt>
                <p class="card-text" style=" color: rgb(100,100,100);">สร้างโปรเจค <br> ตามแบบที่เราต้องการ</p>
            </div>
            <div class="col-4">
                <a href="{{ route('createProject.index')}}">
                    <i class="bx bx-plus" style="font-size: 70px; color: rgb(120,132,232);"></i>
                </a>
            </div>
        </div>
    </div>

    <div class="w3-quarter">
        <div class="w3-card w3-white">
            <div class="w3-container">
                <dt class="card-title mt-3">โปรเจคของฉัน</dt>
                <p class="card-text" style=" color: rgb(100,100,100);">รวบรวมโปรเจคต่างๆ <br> ที่ฉันเคยสร้าง</p>
            </div>
            <div class="col-4">
                <a href="{{ route('myProject.index')}}" type="text">
                    <i class="bx bx-list-ul" style="font-size: 70px; color: rgb(120,132,232);"></i>
                </a>
            </div>
        </div>
    </div>


    <div class="w3-quarter">
        <div class="w3-card w3-white">
            <div class="w3-container">
                <dt class="card-title mt-3"> โปรเจคทั้งหมด</dt>
                <p class="card-text" style=" color: rgb(100,100,100);">ดูโปรเจคทั้งหมด <br> ของผู้อื่นที่มีในระบบ</p>
            </div>
            <div class="col-4">
                <a href="{{ route('Projectall.index')}}" type="text">
                    <i class="bx bx-layer" style="font-size: 70px; color: rgb(120,132,232);"></i>
                </a>
            </div>
        </div>
    </div>




    <div class="w3-quarter">
        <div class="w3-card w3-white">
            <div class="w3-container">
                <dt class="card-title mt-3">ยื่นสอบ</dt>
                <p class="card-text" style=" color: rgb(100,100,100);">ทำการยื่นสอบต่างๆ <br> ที่มีการจัดสอบ</p>
            </div>
            <div class="col-4">
                <a href="{{ url('exam/show')}}" type="text">
                    <i class="bx bx-book-open" style="font-size: 70px; color: rgb(120,132,232);"></i>
                </a>
            </div>
        </div>
    </div>

    <div style="margin-top: 100px;" class="w3-quarter">
        <div class="w3-card w3-white">
            <div class="w3-container">
                <dt class="card-title mt-3">สอบ</dt>
                <p class="card-text" style=" color: rgb(100,100,100);">ดูตารางการสอบ ตรวจสอบคะแนนและส่งไฟล์หลังสอบ</p>
             
                <a href="{{ url('exam/showcalendar')}}" type="text">
                    <i class="bx bx-bot" style="font-size: 70px; color: rgb(120,132,232);"></i>
                </a>
            </div>
        </div>
    </div>
    <div style="margin-top: 100px;" class="w3-quarter">
        <div class="w3-card w3-white">
            <div class="w3-container">
                <dt class="card-title mt-3">ส่งไฟล์สมบูรณ์</dt>
                <p class="card-text" style=" color: rgb(100,100,100);">ส่งไฟล์โปรเจคฉบับสมบูรณ์</p> <br>
            
                <a href="{{ url('filefull')}}" type="text">
                    <i class="bx bx-book-add" style="font-size: 70px; color: rgb(120,132,232);"></i>
                </a>
            </div>
        </div>
    </div>

</div>


@endsection

resources/views/page/student/stdInfor.blade.php
@extends('Layout.masterstd')
@section('title')
@endsection('title')
@section('content')
<div class="section-title">
    <h2>INFORMATION TECHNOLOGY</h2>
    <h4>&nbsp;&nbsp;ข้อมูลส่วนตัว</h4>
</div>
<div class="container">
@foreach($students as $row)
    <div class="row">
        &nbsp;&nbsp;&nbsp;&nbsp;<h4>
            <p class="font-weight-bold">ชื่อ :</p>
        </h4>&nbsp;<h4>{{$row->student_name}}&nbsp;&nbsp;{{$row->student_lastname}}</h4>
    </div>
    <div class="row mt-0">
        &nbsp;&nbsp;&nbsp;&nbsp;<h4>
            <p class="font-weight-bold">รหัสนิสิต :</p>
        </h4>&nbsp;<h4>{{$row->student_id}}</h4>
    </div>
    <div class="row mt-0">
        &nbsp;&nbsp;&nbsp;&nbsp;<h4>
            <p class="font-weight-bold">เบอร์โทรศัพท์ :</p>
        </h4>&nbsp;<h4>{{$row->tel_std}}</h4>
    </div>
    <a href="{{ action('StdinformationController@edit', $row->id) }}" class="btn btn-warning"><i class="fa fa-wrench"></i></a>
    @endforeach
</div>

@endsection

resources/views/page/student/upFileFull.blade.php
@extends('Layout.masterstd')
@section('title')
@endsection('title')
@section('content')

<div class="container">
    @foreach($project as $row)
    <form action="{{ url('upfilefull',$row->projects_id) }}" method="post" enctype="multipart/form-data">
        {{ csrf_field() }}

        <div class="form-group col-7">

            <input type="file" name="file_name" class="form-control" id="customFile" />

        </div>
        <button type="submit" class="btn btn-secondary">อัพโหลด</button>
    </form>
    @endforeach

    <div class="row">
        @foreach($fileproject as $row)

        @endforeach
    </div>
</div>
@endsection